substitutions:
  _REGION: us-central1
  _AR_REPO: odin
  _SERVICE: agent-beta
  _DEPLOY: "true"
  _GATEWAY_JWKS_URL: "https://odin-gateway-237788780100.us-central1.run.app/.well-known/odin/jwks.json"   # REQUIRED if _DEPLOY=true

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

steps:
- name: gcr.io/cloud-builders/docker
  id: "Build image"
  args:
    - build
    - -f
    - Dockerfile.agent-beta
    - -t
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
    - .

- name: gcr.io/cloud-builders/docker
  id: "Push image"
  args:
    - push
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA

# Conditional deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: "Deploy to Cloud Run (conditional)"
  entrypoint: bash
  args:
    - "-lc"
    - |
      if [ "${_DEPLOY}" = "true" ]; then
        if [ -z "${_GATEWAY_JWKS_URL}" ]; then
          echo "ERROR: _GATEWAY_JWKS_URL is required when _DEPLOY=true" >&2
          exit 1
        fi
        gcloud run deploy ${_SERVICE} \
          --project $PROJECT_ID \
          --region ${_REGION} \
          --image ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars ODIN_HTTP_SIGN_REQUIRE=1,ODIN_HTTP_JWKS_URL=${_GATEWAY_JWKS_URL} \
          --min-instances=0 \
          --max-instances=5 \
          --cpu=1 \
          --memory=512Mi \
          --timeout=30s
      else
        echo "Skipping deploy because _DEPLOY=${_DEPLOY}"
      fi
