name: 🚀 Feature Request
description: Suggest a new feature for ODIN Protocol
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify these before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the roadmap for planned features
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature
      placeholder: A clear and concise description of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Gateway
        - Agent Beta
        - Core Libraries
        - JavaScript SDK
        - Python SDK
        - Infrastructure
        - Documentation
        - New Component
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Important for productivity)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Alternative solutions or workarounds you've considered
      placeholder: I've also considered...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: In my application, I need to...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (Optional)
      description: If applicable, suggest an API design
      placeholder: |
        ```python
        # Example API usage
        client.new_feature(param1="value")
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, mockups, or references
      placeholder: Add any other context, screenshots, or links here...
