PYTHONUNBUFFERED: "1"
ODIN_STORAGE_BACKEND: "gcs"
ODIN_GCS_BUCKET: "odin-mesh-data"
ODIN_GCS_PREFIX: "odin"
ODIN_GCS_PUBLIC_HOST: "https://storage.googleapis.com"
ODIN_LEDGER_BACKEND: "firestore"
ODIN_FIRESTORE_COLLECTION: "odin_ledger"
ODIN_SIGN_ROUTES: "/v1/translate,/v1/envelope"
ODIN_SIGN_EMBED: "0"
ODIN_ENFORCE_REQUIRE: "1"
ODIN_SFT_MAPS_DIR: "/app/config/sft_maps"
ODIN_KEYSTORE_PATH: "/secrets/keystore.json"
