name: WIF Auth Check

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: "GCP project ID to use for gcloud context"
        required: false
        default: "valued-lambda-469623-b4"

permissions:
  id-token: write
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SA }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ github.event.inputs.project_id }}

      - name: Verify auth
        shell: bash
        run: |
          echo "Active account:"; gcloud auth list --filter=status:ACTIVE --format='value(account)'
          echo "Token info (email):"; gcloud oauth2 token --impersonate-service-account="${{ secrets.GCP_WIF_SA }}" --audiences="https://www.googleapis.com/auth/cloud-platform" --output=json | jq -r '.email' || true
          echo "WhoAmI:"; gcloud config list account --format='value(core.account)'
          echo "List AR repos (sanity):"; gcloud artifacts repositories list --location=us-central1 --format='table(name,format,location)'
